-- public.processed_request definition

-- Drop table

-- DROP TABLE public.processed_request;

CREATE TABLE public.processed_request (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"data" varchar(255) NULL,
	request_id int8 NULL,
	status varchar(255) NULL,
	processed_at timestamp(6) NULL,
	CONSTRAINT processed_request_pkey PRIMARY KEY (id)
);