-- public.request definition

-- Drop table

-- DROP TABLE public.request;

CREATE TABLE public.request (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"data" varchar(255) NULL,
	status varchar(255) NULL,
	CONSTRAINT request_pkey PRIMARY KEY (id)
);